version: "3"
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: service:local
    container_name: service
    env_file:
      - env-variables.env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all" ]
