apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nanos
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    ssh:
      allow: true